/**
 * This file is autogenerated by `@arcgis/lumina-compiler` - do not edit it manually.
 * Manual edits will be overwritten.
 *
 * This file provides JSX typings for the component libraries your package uses,
 * as well as @arcgis/core typings if you use @arcgis/core.
 *
 * If you need to provide additional typings, create a separate file.
 */
/// <reference types="@arcgis/lumina/typings" />
/// <reference types="@arcgis/core/interfaces" />
/// <reference types="vitest/config" />
/// <reference types="@vitest/browser/jest-dom.d.ts" />
/// <reference types="@vitest/browser/providers/playwright" />
import type { JSX as JSX$0 } from "@esri/calcite-components/dist/types/components";

declare module "@arcgis/lumina" {
  interface ImportStencilElements extends JSX$0.IntrinsicElements {}
}
